(()=>{"use strict";
const canvas=document.getElementById("art"),ctx=canvas.getContext("2d",{alpha:false}),video=document.getElementById("camera"),buttons=[...document.querySelectorAll(".scene-button")];
const ui={number:document.getElementById("sceneNumber"),title:document.getElementById("sceneTitle"),poem:document.getElementById("scenePoem"),daily:document.getElementById("dailyBadge"),scienceButton:document.getElementById("scienceButton"),sciencePanel:document.getElementById("sciencePanel"),aboutButton:document.getElementById("aboutButton"),aboutPanel:document.getElementById("aboutPanel"),scienceTitle:document.getElementById("scienceTitle"),scienceText:document.getElementById("scienceText"),scienceFormula:document.getElementById("scienceFormula"),gestureHelp:document.getElementById("gestureHelp"),sensorNote:document.getElementById("sensorNote"),variation:document.getElementById("variationButton"),capture:document.getElementById("captureButton"),haptic:document.getElementById("hapticButton"),install:document.getElementById("installButton"),permissionCard:document.getElementById("permissionCard"),permissionText:document.getElementById("permissionText"),permissionButton:document.getElementById("permissionButton"),toast:document.getElementById("toast")};
const SCENES={
waves:{index:"01 / 06",title:"Résonance",poem:"Plusieurs vibrations se rencontrent. Leurs accords et leurs silences deviennent lumière.",scienceTitle:"Interférences d’ondes",scienceText:"Les amplitudes de plusieurs ondes se superposent. Quand des crêtes arrivent ensemble, elles se renforcent. Lorsqu’une crête rencontre un creux, elles s’atténuent.",formula:"A = Σ sin(kdᵢ − ωt)",help:"Pose plusieurs doigts pour créer jusqu’à quatre sources. Fais-les glisser pour composer l’image.",sensor:"Interaction multitouch. Une légère vibration peut marquer la création ou la suppression d’une source."},
field:{index:"02 / 06",title:"Invisible",poem:"Le vide n’est pas vide. Une influence silencieuse courbe chaque trajectoire.",scienceTitle:"Champ de deux charges",scienceText:"Un champ associe une direction et une intensité à chaque point de l’espace. Les particules sont des révélateurs graphiques, pas des particules physiques réelles.",formula:"E ∝ q · r⃗ / |r⃗|³",help:"Déplace la seconde charge. Une touche brève inverse sa polarité.",sensor:"Aucun capteur nécessaire. Les vibrations indiquent le changement de polarité lorsqu’elles sont disponibles."},
chaos:{index:"03 / 06",title:"Papillon",poem:"Presque le même départ. Puis deux futurs qui ne se ressemblent plus.",scienceTitle:"Attracteur de Lorenz",scienceText:"Des trajectoires initialement presque identiques se séparent rapidement. Le système reste confiné, mais ne répète jamais exactement le même chemin.",formula:"ẋ=σ(y−x)   ẏ=x(ρ−z)−y   ż=xy−βz",help:"Fais glisser horizontalement pour tourner la sculpture. Touche pour relancer cinq trajectoires voisines.",sensor:"Le gyroscope peut aussi faire tourner la sculpture lorsque l’autorisation est donnée."},
gravity:{index:"04 / 06",title:"Pesanteur",poem:"Le téléphone s’incline. Une pluie d’astres cherche aussitôt un nouveau bas.",scienceTitle:"Accélération et gravité",scienceText:"Les points subissent une accélération commune. Leur vitesse évolue à chaque instant puis ils rebondissent en perdant une partie de leur énergie.",formula:"v⃗(t+Δt)=v⃗(t)+g⃗Δt",help:"Incline le téléphone ou fais glisser ton doigt pour orienter la gravité.",sensor:"Utilise l’orientation du téléphone. Sur certains appareils, une autorisation explicite est requise."},
sound:{index:"05 / 06",title:"Floraison",poem:"La voix ne devient pas donnée. Elle devient seulement forme, souffle et couleur.",scienceTitle:"Spectre sonore",scienceText:"Le microphone mesure temporairement l’intensité de plusieurs bandes de fréquences. L’application ne conserve ni n’envoie aucun enregistrement.",formula:"X(k)=Σ x(n)e^(−i2πkn/N)",help:"Parle, chante, souffle ou frappe doucement dans tes mains pour faire éclore la fleur.",sensor:"Le microphone reste local au navigateur. Il est coupé dès que tu quittes cette œuvre."},
camera:{index:"06 / 06",title:"Chromatique",poem:"Le monde entre par la caméra. Ses couleurs se défont et se recomposent en vitrail vivant.",scienceTitle:"Échantillonnage des couleurs",scienceText:"L’image de la caméra est réduite en cellules. Chaque cellule reprend la couleur moyenne d’une petite zone et devient un fragment du vitrail.",formula:"C̄ = (1/N) Σ Cᵢ",help:"Déplace le téléphone dans ton environnement. Touche l’écran pour changer la géométrie du vitrail.",sensor:"La caméra reste locale et n’est jamais transmise. Elle est coupée en quittant cette œuvre."}};
let W=0,H=0,dpr=1,scene="waves",last=performance.now(),time=0,toastTimer=0,deferredInstall=null,haptic=true,seed=0,paletteIndex=0,pointerDownAt=0,pointerMoved=false;
const pointer={x:innerWidth*.72,y:innerHeight*.56,nx:.72,ny:.56,down:false};
const touches=new Map();
const palettes=[[[8,7,13],[36,90,121],[224,146,65]],[[12,5,15],[119,34,98],[79,194,177]],[[5,13,12],[19,98,70],[237,188,91]],[[16,6,5],[126,38,25],[235,124,43]],[[7,9,19],[38,67,150],[214,103,130]]];
const dayKey=()=>{const d=new Date();return d.getFullYear()*10000+(d.getMonth()+1)*100+d.getDate()};
function seeded(n){let x=Math.sin(n*12.9898+78.233)*43758.5453;return x-Math.floor(x)}
function applyDailySeed(){seed=dayKey();paletteIndex=Math.floor(seeded(seed)*palettes.length);rotation=(seeded(seed+1)-.5)*1.2}
const clamp=(v,a,b)=>Math.max(a,Math.min(b,v)),mix=(a,b,t)=>a+(b-a)*t;
function color(v){const p=palettes[paletteIndex],x=clamp(v,0,1),left=x<.5,t=left?x*2:(x-.5)*2,a=left?p[0]:p[1],b=left?p[1]:p[2];return a.map((q,i)=>Math.round(mix(q,b[i],t)))}
function resize(){W=innerWidth;H=innerHeight;dpr=Math.min(devicePixelRatio||1,2);canvas.width=Math.round(W*dpr);canvas.height=Math.round(H*dpr);canvas.style.width=W+"px";canvas.style.height=H+"px";ctx.setTransform(dpr,0,0,dpr,0,0);pointer.x=pointer.nx*W;pointer.y=pointer.ny*H;low.width=Math.max(90,Math.floor(W/7));low.height=Math.max(140,Math.floor(H/7));waveImage=lctx.createImageData(low.width,low.height);reset(false)}
function showToast(m){clearTimeout(toastTimer);ui.toast.textContent=m;ui.toast.classList.add("visible");toastTimer=setTimeout(()=>ui.toast.classList.remove("visible"),2200)}
function vibrate(pattern=18){if(haptic&&navigator.vibrate)navigator.vibrate(pattern)}
function closePanels(){document.querySelectorAll(".side-panel").forEach(p=>{p.classList.remove("open");p.setAttribute("aria-hidden","true")});ui.scienceButton.setAttribute("aria-pressed","false")}
function setScene(next){if(!SCENES[next])return;stopMedia();scene=next;const s=SCENES[scene];ui.number.textContent=s.index;ui.title.textContent=s.title;ui.poem.textContent=s.poem;ui.scienceTitle.textContent=s.scienceTitle;ui.scienceText.textContent=s.scienceText;ui.scienceFormula.textContent=s.formula;ui.gestureHelp.textContent=s.help;ui.sensorNote.textContent=s.sensor;buttons.forEach(b=>b.classList.toggle("active",b.dataset.scene===scene));closePanels();configurePermission();reset(true);document.querySelector(`[data-scene="${scene}"]`)?.scrollIntoView({behavior:"smooth",block:"nearest",inline:"center"})}
function configurePermission(){ui.permissionCard.hidden=true;if(scene==="gravity"&&!orientationActive){ui.permissionText.textContent="Autoriser l’orientation du téléphone pour guider la gravité.";ui.permissionButton.textContent="Activer le mouvement";ui.permissionButton.onclick=requestOrientation;ui.permissionCard.hidden=false}else if(scene==="sound"&&!audioActive){ui.permissionText.textContent="Autoriser temporairement le microphone pour transformer le son en image.";ui.permissionButton.textContent="Activer le microphone";ui.permissionButton.onclick=startAudio;ui.permissionCard.hidden=false}else if(scene==="camera"&&!cameraActive){ui.permissionText.textContent="Autoriser temporairement la caméra pour créer un vitrail avec les couleurs autour de toi.";ui.permissionButton.textContent="Activer la caméra";ui.permissionButton.onclick=startCamera;ui.permissionCard.hidden=false}}
buttons.forEach(b=>b.onclick=()=>setScene(b.dataset.scene));ui.scienceButton.onclick=()=>{ui.sciencePanel.classList.toggle("open");ui.sciencePanel.setAttribute("aria-hidden",String(!ui.sciencePanel.classList.contains("open")));ui.scienceButton.setAttribute("aria-pressed",String(ui.sciencePanel.classList.contains("open")))};ui.aboutButton.onclick=()=>{closePanels();ui.aboutPanel.classList.add("open");ui.aboutPanel.setAttribute("aria-hidden","false")};document.querySelectorAll("[data-close]").forEach(b=>b.onclick=closePanels);ui.variation.onclick=()=>reset(true);ui.haptic.onclick=()=>{haptic=!haptic;ui.haptic.setAttribute("aria-pressed",String(haptic));showToast(haptic?"Vibrations activées":"Vibrations désactivées")};ui.capture.onclick=capture;
function updatePointer(e){pointer.x=e.clientX;pointer.y=e.clientY;pointer.nx=clamp(pointer.x/W,0,1);pointer.ny=clamp(pointer.y/H,0,1)}
canvas.addEventListener("pointerdown",e=>{pointer.down=true;pointerMoved=false;pointerDownAt=performance.now();updatePointer(e);touches.set(e.pointerId,{x:e.clientX,y:e.clientY});canvas.setPointerCapture?.(e.pointerId);if(scene==="waves"&&touches.size<=4)vibrate(12)});
canvas.addEventListener("pointermove",e=>{if(!pointer.down&&!touches.has(e.pointerId))return;pointerMoved=true;updatePointer(e);if(touches.has(e.pointerId))touches.set(e.pointerId,{x:e.clientX,y:e.clientY});if(scene==="chaos"&&!orientationActive)rotation=(pointer.nx-.5)*2.4;if(scene==="gravity"&&!orientationActive){gravity.x=(pointer.nx-.5)*1.4;gravity.y=(pointer.ny-.5)*1.4}});
canvas.addEventListener("pointerup",e=>{updatePointer(e);touches.delete(e.pointerId);pointer.down=touches.size>0;const tap=performance.now()-pointerDownAt<270&&!pointerMoved;if(tap){if(scene==="waves"){paletteIndex=(paletteIndex+1)%palettes.length;vibrate(14)}if(scene==="field"){fieldPolarity*=-1;vibrate([15,30,15]);showToast(fieldPolarity>0?"Charges de même signe":"Charges opposées")}if(scene==="chaos"){initLorenz();vibrate(18)}if(scene==="camera"){cameraShape=(cameraShape+1)%3;vibrate(12)}}});canvas.addEventListener("pointercancel",e=>{touches.delete(e.pointerId);pointer.down=touches.size>0});
function reset(randomize=true){time=0;if(randomize){paletteIndex=Math.floor(Math.random()*palettes.length);seed=Math.random()*1e6;ui.daily.hidden=true}else ui.daily.hidden=false;ctx.fillStyle="#100907";ctx.fillRect(0,0,W,H);if(scene==="field")initParticles();if(scene==="chaos")initLorenz();if(scene==="gravity")initGravity();if(scene==="sound")initSoundArt()}
const low=document.createElement("canvas"),lctx=low.getContext("2d");let waveImage;
function drawWaves(){const w=low.width,h=low.height,d=waveImage.data,sources=[{x:w*.3,y:h*.59},...([...touches.values()].slice(0,4).map(p=>({x:p.x/W*w,y:p.y/H*h})))];if(sources.length===1)sources.push({x:pointer.nx*w,y:pointer.ny*h});let idx=0,k=.33+paletteIndex*.014;for(let y=0;y<h;y++)for(let x=0;x<w;x++){let a=0;for(const s of sources)a+=Math.sin(k*Math.hypot(x-s.x,y-s.y)-time*2.55);a/=sources.length;let fringe=Math.pow(Math.abs(a),1.55),env=.78+.22*Math.sin((x+y)*.025+time*.35),[r,g,b]=color(clamp(fringe*env,0,1));d[idx++]=r;d[idx++]=g;d[idx++]=b;d[idx++]=255}lctx.putImageData(waveImage,0,0);ctx.imageSmoothingEnabled=true;ctx.drawImage(low,0,0,W,H);for(const s of sources){const x=s.x/w*W,y=s.y/h*H,g=ctx.createRadialGradient(x,y,0,x,y,Math.min(W,H)*.12);g.addColorStop(0,"rgba(255,235,210,.18)");g.addColorStop(1,"rgba(255,255,255,0)");ctx.fillStyle=g;ctx.fillRect(0,0,W,H)}}
let particles=[],fieldPolarity=-1,fieldSpeed=1;
class FieldParticle{constructor(any=true){this.reset(any)}reset(any=false){let ox=W*.31,oy=H*.6,a=Math.random()*Math.PI*2,r=any?Math.random()*Math.max(W,H)*.68:8+Math.random()*38;this.x=ox+Math.cos(a)*r;this.y=oy+Math.sin(a)*r;this.px=this.x;this.py=this.y;this.life=130+Math.random()*430;this.dir=Math.random()>.5?1:-1}update(){this.px=this.x;this.py=this.y;let src=[{x:W*.31,y:H*.6,q:1},{x:pointer.x,y:pointer.y,q:fieldPolarity}],ex=0,ey=0;for(const s of src){let dx=this.x-s.x,dy=this.y-s.y,r2=dx*dx+dy*dy+120,ir=1/Math.pow(r2,1.5);ex+=s.q*dx*ir;ey+=s.q*dy*ir}let m=Math.hypot(ex,ey)||1,dir=fieldPolarity<0?1:this.dir;this.x+=dir*ex/m*fieldSpeed;this.y+=dir*ey/m*fieldSpeed;this.life--;if(this.life<=0||this.x<-30||this.x>W+30||this.y<-30||this.y>H+30||src.some(s=>Math.hypot(this.x-s.x,this.y-s.y)<10))this.reset(false)}draw(){ctx.strokeStyle=`hsla(${32+paletteIndex*38},90%,68%,.18)`;ctx.lineWidth=.75;ctx.beginPath();ctx.moveTo(this.px,this.py);ctx.lineTo(this.x,this.y);ctx.stroke()}}
function initParticles(){fieldSpeed=.75+Math.random()*.7;particles=Array.from({length:Math.round(clamp(W*H/2100,240,700))},()=>new FieldParticle(true))}function drawCharge(x,y,sign){let r=Math.min(W,H)*.1,g=ctx.createRadialGradient(x,y,0,x,y,r),warm=sign>0;g.addColorStop(0,warm?"rgba(247,146,55,.42)":"rgba(83,160,231,.42)");g.addColorStop(.18,warm?"rgba(184,58,25,.15)":"rgba(55,70,180,.16)");g.addColorStop(1,"transparent");ctx.fillStyle=g;ctx.fillRect(x-r,y-r,r*2,r*2);ctx.beginPath();ctx.arc(x,y,4.5,0,Math.PI*2);ctx.fillStyle="#f5eadb";ctx.fill()}function drawField(){ctx.fillStyle="rgba(12,7,8,.052)";ctx.fillRect(0,0,W,H);particles.forEach(p=>{p.update();p.draw()});drawCharge(W*.31,H*.6,1);drawCharge(pointer.x,pointer.y,fieldPolarity)}
let lorenz=[],rotation=-.25,orientationActive=false,orientation={gamma:0,beta:0};function initLorenz(){let base=.01+Math.random()*.03;lorenz=Array.from({length:5},(_,i)=>({x:base+i*.0008,y:0,z:0,points:[],hue:24+i*25+paletteIndex*18}))}function stepL(q,dt){let dx=10*(q.y-q.x),dy=q.x*(28-q.z)-q.y,dz=q.x*q.y-(8/3)*q.z;q.x+=dx*dt;q.y+=dy*dt;q.z+=dz*dt}function project(x,y,z){let c=Math.cos(rotation),s=Math.sin(rotation),rx=x*c-y*s,ry=x*s+y*c,scale=Math.min(W,H)*.0125;return{x:W*.57+rx*scale,y:H*.54+(z-25)*scale*.88+ry*scale*.1}}function drawChaos(){ctx.fillStyle="rgba(10,6,8,.09)";ctx.fillRect(0,0,W,H);if(orientationActive)rotation=orientation.gamma/35;else if(!pointer.down)rotation+=.0007;lorenz.forEach((q,n)=>{for(let i=0;i<5;i++)stepL(q,.005);q.points.push(project(q.x,q.y,q.z));if(q.points.length>950)q.points.shift();for(let i=1;i<q.points.length;i++){let a=q.points[i-1],b=q.points[i],al=i/q.points.length;ctx.strokeStyle=`hsla(${q.hue},85%,${58+n*3}%,${.012+al*.19})`;ctx.lineWidth=.3+al*1.1;ctx.beginPath();ctx.moveTo(a.x,a.y);ctx.lineTo(b.x,b.y);ctx.stroke()}})}
let gravityBodies=[],gravity={x:0,y:.62};function initGravity(){gravityBodies=Array.from({length:Math.round(clamp(W*H/9000,55,130))},()=>({x:Math.random()*W,y:Math.random()*H,vx:(Math.random()-.5)*1.2,vy:(Math.random()-.5)*1.2,r:1.2+Math.random()*3.8,trail:[]}))}function drawGravity(){if(orientationActive){gravity.x=clamp(orientation.gamma/38,-1.25,1.25);gravity.y=clamp(orientation.beta/55,-1.25,1.25)}ctx.fillStyle="rgba(8,6,10,.13)";ctx.fillRect(0,0,W,H);for(const b of gravityBodies){b.vx+=gravity.x*.045;b.vy+=gravity.y*.045;b.vx*=.997;b.vy*=.997;b.x+=b.vx;b.y+=b.vy;if(b.x<b.r){b.x=b.r;b.vx*=-.72}if(b.x>W-b.r){b.x=W-b.r;b.vx*=-.72}if(b.y<b.r){b.y=b.r;b.vy*=-.72}if(b.y>H-b.r){b.y=H-b.r;b.vy*=-.72}b.trail.push({x:b.x,y:b.y});if(b.trail.length>18)b.trail.shift();for(let i=1;i<b.trail.length;i++){let a=b.trail[i-1],c=b.trail[i],al=i/b.trail.length;ctx.strokeStyle=`rgba(235,145,68,${al*.13})`;ctx.lineWidth=b.r*.65;ctx.beginPath();ctx.moveTo(a.x,a.y);ctx.lineTo(c.x,c.y);ctx.stroke()}ctx.beginPath();ctx.arc(b.x,b.y,b.r,0,Math.PI*2);ctx.fillStyle=`rgba(245,${160+Math.round(b.r*12)},${90+Math.round(b.r*12)},.75)`;ctx.fill()}}
let audioCtx,analyser,audioStream,audioData,audioActive=false,soundPetals=[];function initSoundArt(){soundPetals=Array.from({length:96},(_,i)=>({angle:i/96*Math.PI*2,phase:Math.random()*Math.PI*2}))}async function startAudio(){try{audioStream=await navigator.mediaDevices.getUserMedia({audio:{echoCancellation:false,noiseSuppression:false},video:false});audioCtx=new (window.AudioContext||window.webkitAudioContext)();const src=audioCtx.createMediaStreamSource(audioStream);analyser=audioCtx.createAnalyser();analyser.fftSize=256;analyser.smoothingTimeConstant=.82;src.connect(analyser);audioData=new Uint8Array(analyser.frequencyBinCount);audioActive=true;ui.permissionCard.hidden=true;showToast("Le son devient image");vibrate(20)}catch(e){showToast("Microphone non disponible")}}function drawSound(){ctx.fillStyle="rgba(8,5,10,.16)";ctx.fillRect(0,0,W,H);let values=new Uint8Array(128);if(audioActive){analyser.getByteFrequencyData(audioData);values=audioData}else for(let i=0;i<values.length;i++)values[i]=40+25*Math.sin(time*1.4+i*.17);let cx=W*.55,cy=H*.55,base=Math.min(W,H)*.105;for(let i=0;i<soundPetals.length;i++){let p=soundPetals[i],v=values[Math.floor(i/96*values.length)]/255,r=base+v*Math.min(W,H)*.24,w=.018+v*.045,a=p.angle+Math.sin(time*.4+p.phase)*.018,x1=cx+Math.cos(a)*r,y1=cy+Math.sin(a)*r,x0=cx+Math.cos(a)*(base*.35),y0=cy+Math.sin(a)*(base*.35);ctx.strokeStyle=`hsla(${22+i*1.5+paletteIndex*30},88%,${52+v*30}%,${.12+v*.5})`;ctx.lineWidth=1+v*5;ctx.beginPath();ctx.moveTo(x0,y0);ctx.quadraticCurveTo(cx+Math.cos(a+w)*r*.65,cy+Math.sin(a+w)*r*.65,x1,y1);ctx.stroke()}let avg=values.reduce((a,b)=>a+b,0)/values.length/255,g=ctx.createRadialGradient(cx,cy,0,cx,cy,base*(1+avg));g.addColorStop(0,"rgba(250,218,170,.35)");g.addColorStop(1,"transparent");ctx.fillStyle=g;ctx.fillRect(0,0,W,H)}
let cameraStream,cameraActive=false,cameraShape=0,camCanvas=document.createElement("canvas"),camCtx=camCanvas.getContext("2d",{willReadFrequently:true});async function startCamera(){try{cameraStream=await navigator.mediaDevices.getUserMedia({video:{facingMode:"environment",width:{ideal:640},height:{ideal:480}},audio:false});video.srcObject=cameraStream;await video.play();cameraActive=true;ui.permissionCard.hidden=true;showToast("Les couleurs deviennent vitrail");vibrate(20)}catch(e){showToast("Caméra non disponible")}}function drawCamera(){ctx.fillStyle="#100907";ctx.fillRect(0,0,W,H);if(!cameraActive||video.readyState<2){drawCameraFallback();return}let cols=Math.max(9,Math.floor(W/42)),rows=Math.max(14,Math.floor(H/42));camCanvas.width=cols;camCanvas.height=rows;camCtx.drawImage(video,0,0,cols,rows);let data=camCtx.getImageData(0,0,cols,rows).data,cw=W/cols,ch=H/rows;for(let y=0;y<rows;y++)for(let x=0;x<cols;x++){let i=(y*cols+x)*4,r=data[i],g=data[i+1],b=data[i+2],pad=1.4,px=x*cw,py=y*ch;ctx.fillStyle=`rgba(${r},${g},${b},.82)`;ctx.strokeStyle="rgba(12,6,5,.62)";ctx.lineWidth=2;if(cameraShape===0){ctx.beginPath();ctx.roundRect(px+pad,py+pad,cw-pad*2,ch-pad*2,Math.min(cw,ch)*.25);ctx.fill();ctx.stroke()}else if(cameraShape===1){ctx.beginPath();ctx.arc(px+cw/2,py+ch/2,Math.min(cw,ch)*.47,0,Math.PI*2);ctx.fill();ctx.stroke()}else{ctx.beginPath();ctx.moveTo(px+cw/2,py+pad);ctx.lineTo(px+cw-pad,py+ch-pad);ctx.lineTo(px+pad,py+ch-pad);ctx.closePath();ctx.fill();ctx.stroke()}}let vign=ctx.createRadialGradient(W*.5,H*.5,Math.min(W,H)*.18,W*.5,H*.5,Math.max(W,H)*.7);vign.addColorStop(0,"transparent");vign.addColorStop(1,"rgba(8,4,4,.48)");ctx.fillStyle=vign;ctx.fillRect(0,0,W,H)}function drawCameraFallback(){let cell=38;for(let y=0;y<H;y+=cell)for(let x=0;x<W;x+=cell){let n=(Math.sin(x*.018+time)+Math.cos(y*.014-time*.7)+2)/4,[r,g,b]=color(n);ctx.fillStyle=`rgba(${r},${g},${b},.72)`;ctx.fillRect(x+1,y+1,cell-2,cell-2)}}
async function requestOrientation(){try{if(typeof DeviceOrientationEvent!=="undefined"&&typeof DeviceOrientationEvent.requestPermission==="function"){const p=await DeviceOrientationEvent.requestPermission();if(p!=="granted")throw Error()}window.addEventListener("deviceorientation",e=>{orientation.gamma=e.gamma||0;orientation.beta=e.beta||0},{passive:true});orientationActive=true;ui.permissionCard.hidden=true;showToast("Mouvement activé");vibrate(18)}catch(e){showToast("Mouvement non disponible : utilise ton doigt")}}
function stopMedia(){if(scene==="sound"&&audioStream){audioStream.getTracks().forEach(t=>t.stop());audioStream=null;audioActive=false;audioCtx?.close();audioCtx=null}if(scene==="camera"&&cameraStream){cameraStream.getTracks().forEach(t=>t.stop());cameraStream=null;cameraActive=false;video.srcObject=null}}
async function capture(){try{const blob=await new Promise(r=>canvas.toBlob(r,"image/png"));const file=new File([blob],`phenomenes-${scene}-${Date.now()}.png`,{type:"image/png"});if(navigator.canShare?.({files:[file]})){await navigator.share({files:[file],title:"PHÉNOMÈNES",text:"Une œuvre scientifique générée dans PHÉNOMÈNES."})}else{const a=document.createElement("a");a.download=file.name;a.href=URL.createObjectURL(blob);a.click();setTimeout(()=>URL.revokeObjectURL(a.href),1000)}showToast("Œuvre prête à être partagée")}catch(e){if(e.name!=="AbortError")showToast("Partage impossible")}}
function animate(now){let dt=Math.min((now-last)/1000,.05);last=now;time+=dt;if(scene==="waves")drawWaves();else if(scene==="field")drawField();else if(scene==="chaos")drawChaos();else if(scene==="gravity")drawGravity();else if(scene==="sound")drawSound();else drawCamera();requestAnimationFrame(animate)}
window.addEventListener("resize",resize);window.addEventListener("beforeinstallprompt",e=>{e.preventDefault();deferredInstall=e;ui.install.hidden=false});ui.install.onclick=async()=>{if(deferredInstall){deferredInstall.prompt();await deferredInstall.userChoice;deferredInstall=null;ui.install.hidden=true}else showToast(/iphone|ipad|ipod/i.test(navigator.userAgent)?"Safari : Partager → Sur l’écran d’accueil":"Menu du navigateur → Installer l’application")};window.addEventListener("appinstalled",()=>{ui.install.hidden=true;showToast("PHÉNOMÈNES est installée")});if("serviceWorker"in navigator)window.addEventListener("load",()=>navigator.serviceWorker.register("./sw.js").catch(()=>{}));if(/iphone|ipad|ipod/i.test(navigator.userAgent)&&!navigator.standalone)ui.install.hidden=false;window.addEventListener("pagehide",stopMedia);applyDailySeed();resize();setScene("waves");requestAnimationFrame(animate);
})();